// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandRecord } from "./CommandRecord";
import type { UndoStatus } from "./UndoStatus";

export type ActivityEntry = { id: number, repo: string, operation: string, summary: string, started_at: number, duration_ms: number, ok: boolean, local: boolean, toast: boolean, error: string | null, commands: Array<CommandRecord>, undo: UndoStatus, };
