// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiFeature } from "./AiFeature";

export type AiFeatureConfig = { feature: AiFeature, provider_id: string, model_id: string, prompt_template: string, };
