// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiFeature } from "./AiFeature";
import type { AiFeatureConfig } from "./AiFeatureConfig";

export type AiFeatureSummary = { feature: AiFeature, config?: AiFeatureConfig | null, default_prompt_template: string, };
