// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiFeature = "generate_commit" | "recompose" | "conflict_fix" | "explain_changes" | "explain_commit" | "compose_commits" | "stash_message";
