// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderStatus } from "./ProviderStatus";

export type AiSignInStage = { "kind": "browser", url: string, } | { "kind": "device_code", url: string, code: string, } | { "kind": "completed", status: ProviderStatus, };
