// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSignInStage } from "./AiSignInStage";

export type AiSignInEvent = { operation: string, provider: string, stage: AiSignInStage, };
