// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Density } from "./Density";
import type { PullMode } from "./PullMode";
import type { Theme } from "./Theme";

export type AppSettings = { theme: Theme, density: Density, default_branch: string, pull_mode: PullMode, auto_fetch_minutes: number, editor_command: string, terminal_command: string, telemetry_opt_in: boolean, };
