// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppUiPrefs = { palette_recents: Array<string>, last_parent_folder?: string | null, };
