// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileListMode } from "./FileListMode";

export type AppUiPrefs = { palette_recents: Array<string>, last_parent_folder?: string | null, file_list_mode: FileListMode, zoom_percent: number, sidebar_hidden: boolean, inspector_hidden: boolean, syntax_highlighting: boolean, };
