// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthKind } from "./AuthKind";

export type AuthPrompt = { id: string, kind: AuthKind, url: string | null, host: string | null, username: string | null, message: string, fingerprint: string | null, };
