// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthReply = { "kind": "credentials", username: string | null, secret: string, save: boolean, } | { "kind": "trust" } | { "kind": "cancel" } | { "kind": "timed_out" };
