// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthPrompt } from "./AuthPrompt";

export type AuthPromptEvent = { operation: string, prompt: AuthPrompt, };
