// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchFailure } from "./BatchFailure";

export type BatchOutcome = { done: Array<string>, failed: Array<BatchFailure>, };
