// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlameRun = { sha: string, short: string, author: string, email: string, time: number, summary: string, start: number, lines: Array<string>, };
