// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComparedCommit } from "./ComparedCommit";

export type BranchComparison = { merge_base: string, source: string, target: string, commits: Array<ComparedCommit>, files: number, additions: number, deletions: number, };
