// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { NodeKind } from "./NodeKind";

export type CarriedEdge = { row: number, column: number, kind: NodeKind, edge: GraphEdge, };
