// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangeCounts = { modified: number, added: number, deleted: number, renamed: number, untracked: number, conflicted: number, };
