// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckoutTarget = { "kind": "local_branch", name: string, } | { "kind": "remote_branch", name: string, } | { "kind": "tag", name: string, } | { "kind": "commit", sha: string, };
