// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoStash } from "./AutoStash";

export type CheckoutOutcome = { auto_stash: AutoStash, };
