// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloneOptions = { 
/**
 * Fetch only the latest commit of each branch.
 */
shallow: boolean, 
/**
 * Clone without checking out the working tree, for a sparse checkout later.
 */
sparse: boolean, };
