// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphColumn } from "./GraphColumn";

export type ColumnPref = { column: GraphColumn, visible: boolean, width?: number | null, };
