// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitDraft = { summary: string, description: string, summary_trimmed: boolean, excluded: Array<string>, truncated: Array<string>, };
