// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";

export type CommitFile = { path: string, original_path: string | null, status: FileStatus, additions: number | null, deletions: number | null, };
