// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitFile } from "./CommitFile";
import type { GraphRef } from "./GraphRef";
import type { Signature } from "./Signature";

export type CommitDetails = { sha: string, summary: string, body: string, author: Signature, committer: Signature, parents: Array<string>, refs: Array<GraphRef>, files: Array<CommitFile>, };
