// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeGroup } from "./ComposeGroup";

export type ComposeProposal = { groups: Array<ComposeGroup>, excluded: Array<string>, truncated: Array<string>, };
