// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictSegment } from "./ConflictSegment";
import type { ConflictSides } from "./ConflictSides";

export type ConflictFile = { file: string, eol: string, final_newline: boolean, binary: boolean, sides: ConflictSides, segments: Array<ConflictSegment>, };
