// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConflictSegment = { "kind": "text", lines: Array<string>, } | { "kind": "conflict", current: Array<string>, incoming: Array<string>, base: Array<string> | null, };
