// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashOrigin } from "./CrashOrigin";

export type CrashRecord = { id: number, occurred_at: number, origin: CrashOrigin, kind: string, app_version: string, os: string, arch: string, thread: string | null, message: string, location: string | null, stack: string | null, view: string | null, };
