// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrashReport = { kind: string, message: string, stack: string | null, view: string | null, };
