// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePull = { draft: boolean, source_ref: string, target_ref: string, title: string, body: string, };
