// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineKind } from "./DiffLineKind";

export type DiffLine = { kind: DiffLineKind, old_number: number | null, new_number: number | null, text: string, no_newline: boolean, };
