// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorKind = "not_a_repository" | "already_a_repository" | "git_missing" | "git_too_old" | "git_failed" | "invalid_git_output" | "invalid_request" | "stale_hunk" | "commit_failed" | "watch_failed" | "storage_failed" | "auth_failed" | "cancelled" | "local_changes" | "push_rejected" | "not_fast_forward" | "conflict_markers" | "unmerged_branch" | "whitespace_ignored" | "worktree_dirty" | "operation_in_progress" | "not_head" | "merge_commit_in_range" | "internal";
