// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExplanationItem } from "./ExplanationItem";

export type Explanation = { items: Array<ExplanationItem>, excluded: Array<string>, truncated: Array<string>, };
