// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";

export type FileRevision = { sha: string, short: string, summary: string, author: string, email: string, time: number, path: string, status: FileStatus, };
