// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeArea } from "./ChangeArea";
import type { FileStatus } from "./FileStatus";

export type FileChange = { path: string, original_path: string | null, area: ChangeArea, status: FileStatus, };
