// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileAtRevision = { "kind": "text", text: string, size: number, eol: string, } | { "kind": "binary", size: number, };
