// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

export type FileDiff = { path: string, original_path: string | null, binary: boolean, old_size: number | null, new_size: number | null, hunks: Array<DiffHunk>, };
