// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Repositories } from "./Repositories";
import type { ScannedFolder } from "./ScannedFolder";

export type FolderRemoved = { folder: ScannedFolder, repositories: Repositories, };
