// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitBrief } from "./CommitBrief";
import type { ForceLease } from "./ForceLease";

export type ForcePushPlan = { lease: ForceLease, upstream: string, replaced: Array<CommitBrief>, };
