// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForceLease } from "./ForceLease";
import type { RevisionRange } from "./RevisionRange";

export type ForcePushPlan = { lease: ForceLease, upstream: string, replaced: RevisionRange, };
