// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForceLease = { remote: string, branch: string, remote_ref: string, expected_sha: string, };
