// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitFlowConfig = { production: string, development: string, feature: string, release: string, hotfix: string, version_tag: string, };
