// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHost = { id: string, host: string, ssh_key_path: string | null, https_user: string | null, key_kind: string | null, key_fingerprint: string | null, has_public_key: boolean, };
