// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHostDraft = { host: string, ssh_key_path: string | null, https_user: string | null, };
