// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarriedEdge } from "./CarriedEdge";
import type { GraphRow } from "./GraphRow";

export type GraphPage = { rows: Array<GraphRow>, carried: Array<CarriedEdge>, total: number, };
