// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";
import type { GraphEdge } from "./GraphEdge";
import type { GraphRef } from "./GraphRef";
import type { NodeKind } from "./NodeKind";

export type GraphRow = { sha: string | null, parents: Array<string>, summary: string, author: Author | null, time: number | null, refs: Array<GraphRef>, kind: NodeKind, column: number, edges: Array<GraphEdge>, };
