// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphEdge = { lane: number, parent_row: number | null, parent_column: number | null, };
