// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefSelector } from "./RefSelector";

export type GraphVisibility = { "kind": "all" } | { "kind": "current_and_upstream" } | { "kind": "refs", refs: Array<RefSelector>, };
