// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Head = { "kind": "branch", name: string, sha: string, } | { "kind": "detached", sha: string, } | { "kind": "unborn", branch: string, };
