// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookEntry = { name: string, path: string, active: boolean, reason: string | null, hash: string, approved: boolean, };
