// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookEnd } from "./HookEnd";

export type HookOutcome = { end: HookEnd, exit_code: number | null, stops_git: boolean, };
