// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookEntry } from "./HookEntry";

export type HookScript = { hook: HookEntry, content: string, truncated: boolean, };
