// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookStream } from "./HookStream";

export type HookOutput = { id: string, stream: HookStream, text: string, };
