// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevisionRange } from "./RevisionRange";

export type IntegrationPreview = { incoming: RevisionRange, outgoing: RevisionRange, fast_forward: boolean, };
