// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraIssue } from "./JiraIssue";

export type JiraIssueLookup = { key: string, issue: JiraIssue | null, failure: string | null, };
