// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraKind } from "./JiraKind";
import type { JiraProject } from "./JiraProject";

export type JiraConnection = { id: string, kind: JiraKind, site: string, host: string, email: string | null, display_name: string, projects: Array<JiraProject>, created_at: number, };
