// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraStatusCategory } from "./JiraStatusCategory";

export type JiraIssue = { key: string, summary: string, status: string, status_category: JiraStatusCategory, issue_type: string, project: string, assignee: string | null, updated_at: string, web_url: string, connection_id: string, };
