// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchpadPull } from "./LaunchpadPull";

export type LaunchpadPulls = { pulls: Array<LaunchpadPull>, total: number | null, capped: boolean, };
