// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequest } from "./PullRequest";
import type { PullRole } from "./PullRole";
import type { RepoRef } from "./RepoRef";

export type LaunchpadPull = { connection_id: string, repo: RepoRef, role: PullRole, draft: boolean, pull: PullRequest, local_path: string | null, };
