// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LostKind } from "./LostKind";

export type LostCommit = { sha: string, summary: string, author: string, time: number, kind: LostKind, };
