// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformConnection } from "./PlatformConnection";
import type { RepoRef } from "./RepoRef";

export type MatchedRepo = { connection: PlatformConnection, remote: string, repo: RepoRef, };
