// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationStep } from "./OperationStep";

export type OperationDetail = { current: string, incoming: string | null, message: string, step: OperationStep | null, resolved: Array<string>, stopped_edit?: string | null, };
