// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformKind } from "./PlatformKind";

export type PlatformConnection = { id: string, kind: PlatformKind, host: string, name: string, insecure_tls: boolean, created_at: number, };
