// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrFile } from "./PrFile";
import type { PullRequest } from "./PullRequest";

export type PrDetail = { pull: PullRequest, files: Array<PrFile>, files_total: number | null, files_capped: boolean, };
