// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderStatus = { "kind": "ready" } | { "kind": "signed_out" } | { "kind": "key_missing" } | { "kind": "key_rejected" } | { "kind": "unreachable", message: string, } | { "kind": "check_failed", message: string, };
