// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyChange } from "./ApiKeyChange";
import type { AuthMode } from "./AuthMode";

export type ProviderUpdate = { id: string, auth_mode: AuthMode, name: string, base_url?: string | null, api_key: ApiKeyChange, };
