// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKeyChange } from "./ApiKeyChange";

export type ProviderUpdate = { id: string, name: string, base_url?: string | null, executable_path?: string | null, api_key: ApiKeyChange, };
