// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrState } from "./PrState";

export type PullRequest = { draft: boolean, number: number, title: string, body: string, state: PrState, source_ref: string, target_ref: string, author: string, created_at: string, updated_at: string, mergeable: boolean | null, web_url: string, };
