// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequest } from "./PullRequest";

export type PullList = { pulls: Array<PullRequest>, total: number | null, capped: boolean, };
