// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestDisclosure } from "./PullRequestDisclosure";

export type PullRequestDraft = { title: string, description: string, title_trimmed: boolean, sent: PullRequestDisclosure, };
