// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PullRequestDisclosure = { commit_messages: number, files: number, additions: number, deletions: number, provider_name: string, excluded: Array<string>, truncated: Array<string>, };
