// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";

export type RebaseTodo = { sha: string, summary: string, author: Author, is_merge: boolean, pushed: boolean, };
