// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebaseOutcome } from "./RebaseOutcome";

export type RebaseResult = { outcome: RebaseOutcome, pushed: boolean, dropped_all: boolean, };
