// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebaseTodo } from "./RebaseTodo";

export type RebasePlan = { base: string, commits: Array<RebaseTodo>, pushed: boolean, };
