// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RebaseStep = { "kind": "pick", sha: string, } | { "kind": "reword", sha: string, message: string, } | { "kind": "squash", sha: string, message: string, } | { "kind": "fixup", sha: string, } | { "kind": "drop", sha: string, } | { "kind": "edit", sha: string, };
