// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AheadBehind } from "./AheadBehind";
import type { ChangeCounts } from "./ChangeCounts";

export type RecentStatus = { path: string, exists: boolean, branch: string | null, unborn: boolean, ahead_behind: AheadBehind | null, counts: ChangeCounts | null, worktrees: number, unreadable: string | null, };
