// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecomposeGroup } from "./RecomposeGroup";

export type RecomposeProposal = { groups: Array<RecomposeGroup>, excluded: Array<string>, };
