// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecomposeFile } from "./RecomposeFile";

export type RecomposePreview = { base: string, head: string, pushed: boolean, files: Array<RecomposeFile>, };
