// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";
import type { RecomposeHunk } from "./RecomposeHunk";

export type RecomposeFile = { path: string, status: FileStatus, binary: boolean, whole_file_only: boolean, hunks_omitted: string | null, hunks: Array<RecomposeHunk>, };
