// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecomposeChange } from "./RecomposeChange";

export type RecomposeGroup = { message: string, changes: Array<RecomposeChange>, };
