// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecomposeChange = { "kind": "file", path: string, } | { "kind": "hunk", id: string, } | { "kind": "lines", id: string, lines: Array<number>, };
