// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReflogEntry = { index: number, selector: string, sha: string, previous_sha: string | null, action: string, message: string, time: number, summary: string, exists: boolean, };
