// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedRepo } from "./ManagedRepo";
import type { Repositories } from "./Repositories";

export type RepoRemoved = { removed: ManagedRepo, repositories: Repositories, };
