// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnPref } from "./ColumnPref";
import type { GraphVisibility } from "./GraphVisibility";

export type RepoUiPrefs = { columns: Array<ColumnPref>, collapsed_folders: Array<string>, branch_visibility: GraphVisibility, };
