// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullMode } from "./PullMode";

export type RepoSettings = { pull_mode: PullMode | null, ssh_key_path?: string | null, 
/**
 * Missing or false: fetch does not move submodules.
 */
submodule_update_on_fetch?: boolean | null, };
