// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedRepo } from "./ManagedRepo";
import type { ScannedFolder } from "./ScannedFolder";

export type Repositories = { folders: Array<ScannedFolder>, repos: Array<ManagedRepo>, };
