// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitBrief } from "./CommitBrief";

export type RevisionRange = { count: number, commits: Array<CommitBrief>, };
