// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScannedFolder = { path: string, depth: number, scanned_at: number, repos: Array<string>, skipped: Array<string>, };
