// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigningFormat } from "./SigningFormat";

export type SigningConfig = { sign_commits: boolean, sign_tags: boolean, format: SigningFormat, key: string, program: string, };
