// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotInfo = { ref: string, time: number, action: string, description: string, head_sha: string | null, branch: string | null, files_changed: number, };
