// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StashFile } from "./StashFile";

export type StashDetails = { index: number, sha: string, message: string, base_sha: string | null, untracked_sha: string | null, files: Array<StashFile>, };
