// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmoduleStatus } from "./SubmoduleStatus";

export type Submodule = { name: string, path: string, url: string, branch: string | null, status: SubmoduleStatus, recorded: string, checked_out: string | null, };
