// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SwitchStash = { branch: string, sha: string, message: string, created_at: number, index: number, };
