// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TabGroupColor = "cyan" | "blue" | "purple" | "magenta" | "pink" | "red" | "orange" | "yellow" | "green" | "mint";
