// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabGroup } from "./TabGroup";

export type TabSession = { tabs: Array<string>, active: number, groups: Array<TabGroup>, };
