// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolEntry } from "./ToolEntry";

export type ToolsDetected = { compare: Array<ToolEntry>, editors: Array<ToolEntry>, git_merge_tool: string | null, git_diff_tool: string | null, };
