// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UndoStatus = { "kind": "available", scope: string, } | { "kind": "unavailable", reason: string, } | { "kind": "undone" };
