// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AheadBehind } from "./AheadBehind";

export type Upstream = { name: string, ahead_behind: AheadBehind | null, };
