// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentitySource } from "./IdentitySource";
import type { Transport } from "./Transport";

export type UrlIdentity = { transport: Transport, source: IdentitySource, host: string | null, ssh_key_path: string | null, https_user: string | null, };
