// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { OperationKind } from "./OperationKind";
import type { ProviderKind } from "./ProviderKind";

export type UsageRecord = { id: number, occurred_at: number, app_version: string, event: OperationKind, ok: boolean, error_kind: ErrorKind | null, duration_ms: number, count: number, correlation_id: number, provider?: ProviderKind | null, model?: string | null, };
