// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Wip = { path: string, name: string, branch: string | null, changes: number, unpushed: number, unreadable: string | null, };
