// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeIntegration = { "kind": "integrated", target_sha: string, cleaned_up: boolean, } | { "kind": "conflicts", worktree: string, };
