export const SHORTCUTS = {
  palette: "⌘K",
  search: "⌘F",
  commit: "⌘↵",
  undo: "⌘Z",
  redo: "⌘⇧Z",
  createBranch: "⌘B",
  stash: "⌘⇧S",
  fetch: "⌘⇧F",
  pull: "⌘⇧L",
  push: "⌘⇧P",
  revealHead: "⌘⇧H",
  newTab: "⌘T",
  closeTab: "⌘W",
  reopenClosedTab: "⌘⇧T",
  nextTab: "⌃⇥",
  previousTab: "⌃⇧⇥",
  openRepository: "⌘O",
  cloneRepository: "⌘⇧C",
  createRepository: "⌘N",
  settings: "⌘,",
  activity: "⌘⇧Y",
} as const;
